export const SET_LOADING = "SET_LOADING";
export const SET_TOKEN = "SET_TOKEN";
export const SET_ERROR = "SET_ERROR";
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VALIDATE_OTP = "VALIDATE_OTP";
export const VALIDATE_OTP_SUCCESS = "VALIDATE_OTP_SUCCESS";
export const VALIDATE_OTP_FAILURE = "VALIDATE_OTP_FAILURE";

export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILURE = "FORGET_PASSWORD_FAILURE";

export const SETUP_RESTAURANT_ACCOUNT = "SETUP_RESTAURANT_ACCOUNT";
export const SETUP_RESTAURANT_ACCOUNT_SUCCESS = "SETUP_RESTAURANT_ACCOUNT_SUCCESS";
export const SETUP_RESTAURANT_ACCOUNT_FAILURE = "SETUP_RESTAURANT_ACCOUNT_FAILURE";