export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const GET_CART_ITEM = "GET_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELETE_CART_ITEMS = "DELETE_CART_ITEMS";
export const SELECT_RESTAURANT_FOR_CART = "SELECT_RESTAURANT_FOR_CART";
export const SET_RESTAURANT_CART = "SET_RESTAURANT_FOR_CART";
export const UPDATE_CART_TOTAL = "UPDATE_CART_TOTAL";