export const ORDER_LOADING = "ORDER_LOADING";

export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";

export const GET_USER_ORDER = "GET_USER_ORDER";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAILURE = "GET_USER_ORDER_FAILURE";

export const POST_USER_ORDER = "POST_USER_ORDER";
export const POST_USER_ORDER_SUCCESS = "POST_USER_ORDER_SUCCESS";
export const POST_USER_ORDER_FAILURE = "POST_USER_ORDER_FAILURE";
