export const ORDER_LOADING = "ORDER_LOADING";

export const GET_USER_ORDER = "GET_USER_ORDER";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAILURE = "GET_USER_ORDER_FAILURE";
