export const SET_RESTAURANT_LOADING = "SET_RESTAURANT_LOADING";
export const SET_SELECTED_BUILDINGS = "SET_SELECTED_BUILDINGS";

export const GET_RESTAURANT = "GET_RESTAURANT";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAILURE = "GET_RESTAURANT_FAILURE";

export const GET_RESTAURANT_BY_ID = "GET_RESTAURANT_BY_ID";
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAILURE = "GET_RESTAURANT_BY_ID_FAILURE";

export const GET_RESTAURANT_MENU = "GET_RESTAURANT_MENU";
export const GET_RESTAURANT_MENU_SUCCESS = "GET_RESTAURANT_MENU_SUCCESS";
export const GET_RESTAURANT_MENU_FAILURE = "GET_RESTAURANT_MENU_FAILURE";

export const GET_BUILDING = "GET_BUILDING";
export const GET_BUILDING_SUCCESS = "GET_BUILDING_SUCCESS";
export const GET_BUILDING_FAILURE = "GET_BUILDING_FAILURE";
