export const PROFILE_LOADING = "PROFILE_LOADING";

export const POST_REVIEW = "POST_REVIEW";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAILURE = "POST_REVIEW_FAILURE";
